spec:
  template:
    spec:
      containers:
      - image: quay.io/sustainable_computing_io/kepler-estimator:latest
        imagePullPolicy: Always
        name: estimator
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - name: cfm
          mountPath: /etc/config
          readOnly: true
      - name: kepler-exporter
        image: quay.io/sustainable_computing_io/kepler:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        args:
        - until [ -e /tmp/estimator.sock ]; do sleep 1; done && /usr/bin/kepler -address
          0.0.0.0:9102 -enable-gpu=true -enable-cgroup-id=true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - emptyDir: {}
        name: tmp
      - name: cfm
        configMap:
          name: kepler-estimator-cfm
