apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler-cfm
data:
  MODEL_CONFIG: |
      CONTAINER_COMPONENTS_ESTIMATOR="true"
      CONTAINER_COMPONENTS_INIT_URL=https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentPower/CgroupOnly/ScikitMixed.zip
---
apiVersion: batch/v1
kind: Job
metadata:
  name: estimator-job
spec:
  template:
    spec:
      containers:
      - image: quay.io/sustainable_computing_io/kepler-estimator:latest
        imagePullPolicy: IfNotPresent
        name: estimator
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - name: cfm
          mountPath: /etc/kepler/kepler.config
          readOnly: true
        command: ["python3", "src/estimator_test.py"]
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: tmp
      - name: cfm
        configMap:
          name: kepler-cfm